replicaCount: 2

image:
  repository: ghcr.io/damienjburks/affirmation-system
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  className: nginx
  enabled: true
  host: affirmations.dsb-hub.local
  annotations:
    cert-manager.io/cluster-issuer: mkcert-issuer
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  tls:
    enabled: true
    host: affirmations.dsb-hub.local  
    secretName: affirmation-system-cert-tls

resources: {}